name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # "environment" must match the name of your GitHub environment
    environment: prod

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./codebases/message_server/"
          target: ~/message-server

      - name: Build and run on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ec2-user"
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            cd ~/message_server
            docker build --pull -t message_server: latest.
            docker stop message_server || true
            docker rm message_server || true
            docker image prune -f || true
            docker run -d \
              --name message_server \
              --restart unless-stopped \
              -p 5002:5002 \
              -e APP_ENV=PRODUCTION \
              -e POSTGRES_USER='${{ secrets.POSTGRES_USER }}' \
              -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' \
              -e POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}' \
              -e POSTGRES_DB='postgres' \
              message-server: latest
